import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const glossaryTerms = [
  { term: "Capital Expenditure", definition: "Funds used to acquire or upgrade physical assets such as buildings, roads, and equipment." },
  { term: "Recurrent Expenditure", definition: "Ongoing costs for running day-to-day operations, including salaries and maintenance." },
  { term: "IGR (Internally Generated Revenue)", definition: "Income generated by the state through taxes, fees, and other local sources." },
  { term: "FAAC (Federation Account Allocation Committee)", definition: "Federal allocation distributed to states from the nation's revenue." },
  { term: "Fiscal Year", definition: "The 12-month period used for calculating annual financial statements." },
]

export function BudgetGlossary() {
  return (
    <Card className="bg-secondary text-foreground">
      <CardHeader>
        <CardTitle className="text-primary">Budget Glossary</CardTitle>
      </CardHeader>
      <CardContent>
        <dl className="space-y-2">
          {glossaryTerms.map(({ term, definition }) => (
            <div key={term}>
              <dt className="font-semibold text-primary">{term}</dt>
              <dd className="text-muted-foreground">{definition}</dd>
            </div>
          ))}
        </dl>
      </CardContent>
    </Card>
  )
}

