
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

export function BudgetGlossary() {
  const glossaryItems = [
    {
      term: "Capital Expenditure",
      definition:
        "Funds allocated for the acquisition or maintenance of fixed assets like buildings, land, infrastructure, and equipment that have a long-term economic benefit.",
    },
    {
      term: "Recurrent Expenditure",
      definition:
        "Regular spending on operational costs such as salaries, wages, maintenance, and other day-to-day expenses required to run government services.",
    },
    {
      term: "IGR (Internally Generated Revenue)",
      definition:
        "Revenue that a state generates within its jurisdiction through taxes, fees, fines, and other local sources, independent of federal allocations.",
    },
    {
      term: "FAAC (Federation Account Allocation Committee)",
      definition:
        "The committee responsible for distributing revenue from the Federation Account to the Federal, State, and Local Governments in Nigeria.",
    },
    {
      term: "Budget Deficit",
      definition:
        "When government expenditures exceed revenues, requiring borrowing or drawing from reserves to cover the shortfall.",
    },
    {
      term: "Budget Surplus",
      definition:
        "When government revenues exceed expenditures, resulting in excess funds that can be saved or invested.",
    },
    {
      term: "Fiscal Year",
      definition:
        "A 12-month period used by governments for accounting purposes and budget execution, which may not coincide with the calendar year.",
    },
    {
      term: "Statutory Allocation",
      definition:
        "Revenue distributed to states from the Federation Account based on a predetermined formula as mandated by law.",
    },
    {
      term: "Grants",
      definition:
        "Financial assistance provided by external entities (federal government, international organizations, etc.) that doesn't require repayment.",
    },
    {
      term: "Loans",
      definition:
        "Borrowed funds that must be repaid with interest over a specified period, used to finance budget deficits or specific projects.",
    },
  ]

  return (
    <Card>
      <CardHeader>
        <CardTitle>Budget Glossary</CardTitle>
        <CardDescription>Key terms and definitions related to state budgets</CardDescription>
      </CardHeader>
      <CardContent>
        <Accordion type="single" collapsible className="w-full">
          {glossaryItems.map((item, index) => (
            <AccordionItem key={index} value={`item-${index}`}>
              <AccordionTrigger className="font-medium">{item.term}</AccordionTrigger>
              <AccordionContent className="text-muted-foreground">{item.definition}</AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </CardContent>
    </Card>
  )
}






// import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

// const glossaryTerms = [
//   { term: "Capital Expenditure", definition: "Funds used to acquire or upgrade physical assets such as buildings, roads, and equipment." },
//   { term: "Recurrent Expenditure", definition: "Ongoing costs for running day-to-day operations, including salaries and maintenance." },
//   { term: "IGR (Internally Generated Revenue)", definition: "Income generated by the state through taxes, fees, and other local sources." },
//   { term: "FAAC (Federation Account Allocation Committee)", definition: "Federal allocation distributed to states from the nation's revenue." },
//   { term: "Fiscal Year", definition: "The 12-month period used for calculating annual financial statements." },
// ]

// export function BudgetGlossary() {
//   return (
//     <Card className="bg-secondary text-foreground">
//       <CardHeader>
//         <CardTitle className="text-primary">Budget Glossary</CardTitle>
//       </CardHeader>
//       <CardContent>
//         <dl className="space-y-2">
//           {glossaryTerms.map(({ term, definition }) => (
//             <div key={term}>
//               <dt className="font-semibold text-primary">{term}</dt>
//               <dd className="text-muted-foreground">{definition}</dd>
//             </div>
//           ))}
//         </dl>
//       </CardContent>
//     </Card>
//   )
// }

